FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["simple-mvc.csproj", "./"]
RUN dotnet restore "simple-mvc.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "simple-mvc.csproj" -c Release -o /app/build

FROM build as publish
RUN dotnet publish "simple-mvc.csproj" -c Release -o /app/publish

FROM base as Final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "simple-mvc.dll"]


